parameters:
#    on_call_admin.example.class: OnCall\Bundle\AdminBundle\Example

services:
#    on_call_admin.example:
#        class: %on_call_admin.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
